services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tour_agency_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tour_agency_db -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "sleep 20 &&
             python manage.py migrate &&
             python create_superuser.py &&
             python manage.py loaddata tours/fixtures/test_data.json &&
             python manage.py runserver 0.0.0.0:6602"
    volumes:
      - .:/app
    ports:
      - "6602:6602"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=tour_agency_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  postgres_data:
